import type { ActaConfig } from './types';

export const cerritoConfig: ActaConfig = {
  docFields: {
    municipio: 'EL CERRITO',
    municipioNit: '',
    contrato: '01 de 2014',
    tipoActa: '',
    actaYear: String(new Date().getFullYear()),
    actaFecha: '',
    actaNumero: '',
    actaReferenciaAnterior: '',
    smmlvPresupuesto: '',
    munNombre: '',
    munCc: '',
    munCcCiudad: '',
    munCargo: '',
    munPosesionFecha: '',
    conNombre: 'GLORIA LUCIA ESCALANTE MANZANO',
    conCc: '',
    conCcCiudad: '',
    conEmpresa: 'UNIÓN TEMPORAL ALUMBRADO PÚBLICO EL CERRITO',
    conNit: '',
    intNombre: '',
    intCc: '',
    intCcCiudad: '',
    intEmpresa: '',
    intCargo: '',
  },

  consideraciones: [
    'Que el artículo 2 de la Constitución Política de Colombia de 1991 señala que son fines esenciales del Estado. Servir a la comunidad, promover la prosperidad general y garantizar la efectividad de los principios, derechos y deberes consagrados en la constitución.',
    'Que de conformidad con el artículo 315 de la carta política de Colombia, corresponde a los alcaldes cumplir y hacer cumplir la constitución, la ley, los decretos del gobierno, las ordenanzas, los acuerdos de los concejos y dirigir la acción administrativa del municipio; asegurar el cumplimiento de las funciones y la prestación de los servicios a su cargo, en concordancia con el artículo 941 de la Ley 136 de 1994 modificado por el artículo 29 de la ley 1551 de 2012.',
    'Que el artículo 365 de la Constitución Política señala que los servicios públicos son inherentes a la finalidad social del Estado, debiendo garantizar su prestación eficiente a todos los habitantes del territorio nacional.',
    'Que EL MUNICIPIO abrió proceso de licitación pública No L-010-2014 para contratar mediante el sistema de CONCESION, la prestación de servicio de Inversión, Administración, Operación, Mantenimiento, Reposición, Expansión y Desarrollo Tecnológico asociado al sistema de alumbrado público del Municipio de El Cerrito, suministrando el CONCESIONARIO a pleno costo los elementos, y asumiendo en fin, todo lo inherente y relacionado con el servicio de Alumbrado Público en todo el territorio del Municipio, a cambio de la remuneración pactada por las partes.',
    'Que EL MUNICIPIO adjudicó al CONCESIONARIO la licitación mediante Resolución No. 0934 del 30 de diciembre del 2014 modificada por la Resolución No. 0010 del 20 de enero de 2015.',
    'Que, adjudicado el proceso de licitación, EL MUNICIPIO y EL CONCESIONARIO firmaron el contrato de concesión No. {{CONTRATO}} de fecha 21 enero de 2015.',
    'Que el servicio de alumbrado público comprende las actividades de suministro de energía al sistema de alumbrado público, la administración, la operación, el mantenimiento, la modernización, la reposición y la expansión del sistema de alumbrado público.',
    'Que el artículo 350 del Estatuto Tributario Ley 1819 de 2016 dispone que el impuesto de alumbrado público, como actividad inherente al servicio de energía eléctrica, se destina exclusivamente a la prestación, mejora, modernización y ampliación de la prestación del servicio de alumbrado público, incluyendo el suministro, administración, operación, mantenimiento, expansión y desarrollo tecnológico asociado.',
    'Que con base en la anterior autorización, en la Cláusula Primera del otrosí No. 4 al contrato de Concesión No {{CONTRATO}}, del 5 de diciembre del 2017, se encuentra "PARAGRAFO CUARTO: Cualquier excedente que el contratante recaude por concepto del tributo de alumbrado público será invertido en obras de expansión y/o modernización que ejecutará el concesionario, para cuyo propósito se suscribirán actas de obra en las que se establezca con exactitud el monto de la obra de expansión o modernización o iluminación ornamental y navideña en los espacios públicos del Municipio a ejecutar, la fuente de financiamiento, las especificaciones técnicas, la forma de pago y la disposición de los recursos necesarios para garantizar su mantenimiento preventivo y correctivo al formar parte de la infraestructura concesionada, así como a la actividad de iluminación ornamental y navideña en los espacios públicos del Municipio"',
    'El desarrollo de tales actividades dependerá de la existencia de recursos suficientes para ellas, y para su realización solo requerirá de actas firmadas para el efecto, por el Municipio y el Concesionario.',
    'Que en reunión extraordinaria del 22 de mayo de 2025 se presentaron los diferentes proyectos de expansión, en el cual la administración municipal aprobó los proyectos que se describen en el presente documento con los valores determinados para ello.',
    'Que El Municipio cuenta con los recursos necesarios para la ejecución de la obra de expansión, según los excedentes a favor del Municipio de El Cerrito que se encuentran en la cuenta de la Fiducia del Banco de Bogotá y la destinación para la expansión por valor de {{VALOR_TOTAL}}.',
  ],

  clausulas: [
    { title: 'CLÁUSULA PRIMERA — OBJETO', content: '"Ejecutar por parte de la empresa Unión Temporal Alumbrado Público El Cerrito las diferentes obras relacionadas en la presente acta.' },
    { title: 'CLÁUSULA SEGUNDA — VALOR DEL PROYECTO', content: 'El valor total del proyecto de expansión es de {{VALOR_TOTAL}} así:' },
    { title: 'PARÁGRAFO — FUENTE DE FINANCIAMIENTO', content: 'Los proyectos de expansión del sistema de alumbrado público en el municipio de El Cerrito se ejecutará con los saldos del recaudo del Impuesto de Alumbrado Público, determinados en fiducia con corte a 30 de junio de 2025.' },
    { title: 'CLÁUSULA TERCERA — ALCANCE DE LAS OBRAS A EJECUTAR', content: 'Realizar las obras de expansión y puesta en funcionamiento en los sectores relacionados en la presente acta en zona urbana y rural dentro del municipio de El Cerrito.' },
    { title: 'CLÁUSULA CUARTA — ESPECIFICACIONES TÉCNICAS', content: 'El proyecto de iluminación se realizará con luminarias LED de 35, 56 y 80 W, postes metálicos y de fibra de vidrio, cable # 6 aislado y red trenzada 2x4 + 4.' },
    { title: 'CLÁUSULA QUINTA — OPERACIÓN Y MANTENIMIENTO', content: 'Estará a cargo de la Unión Temporal Alumbrado Público El Cerrito - UTAP en el marco del contrato de Concesión No {{CONTRATO}}.' },
    { title: 'CLÁUSULA SEXTA — FORMA DE PAGO', content: 'El MUNICIPIO pagará al CONCESIONARIO el valor total de la presente Acta de Obra No. {{NUM_ACTA}}, a la firma del acta de inicio con saldos de fiducia del impuesto de alumbrado público correspondiente a la vigencia 2025, la suma de {{VALOR_TOTAL}}, previa aprobación de garantías.' },
    { title: 'CLÁUSULA SÉPTIMA — VALORES PRESUPUESTO DE EXPANSIÓN', content: 'Los valores que conforman el presupuesto corresponden a las UCAPs aceptadas por el Municipio dentro de la oferta económica y las UCAPs nuevas aprobadas mediante la presente Acta de Obra así:' },
    { title: 'CLÁUSULA OCTAVA — PLAZO DE EJECUCIÓN', content: 'El plazo para la ejecución de los proyectos de Iluminación contemplados en la presente Acta de Obra es de ciento ochenta (180) días hábiles contados a partir de la firma del acta de inicio, previa aprobación de las garantías por parte del Municipio.' },
    { title: 'CLÁUSULA NOVENA — GARANTÍAS', content: 'EL CONCESIONARIO deberá garantizar la ejecución del presente convenio, por tanto, deberá amparar a favor del Municipio a través de cualquiera de los mecanismos de cobertura de riesgo permitidos por el Decreto 1082 de 2015.' },
    { title: 'CLÁUSULA DÉCIMA — PERFECCIONAMIENTO, LEGALIZACIÓN', content: 'La presente acta se considerará perfeccionada con la suscripción del presente documento por cada una de las partes, legalizada con el acta de aprobación de las polizas y en ejecución con la suscripción del acta de inicio.\n\nPara constancia se firma por las partes en dos (2) ejemplares al mismo tenor a los veintiun (21) días del mes de Julio del año dos mil veinticinco (2025).' },
  ],
};
