import type { ActaConfig } from './types';

export const circasiaConfig: ActaConfig = {
  logoUrl: '/assets/images/logo-circasia.jpg',
  garantiaCumplimientoTitle: 'I. GARANTÍA DE CUMPLIMIENTO DEL CONTRATO Y DEVOLUCIÓN DEL PAGO ANTICIPADO:',
  garantiaRceTitle: 'II. GARANTÍA DE RESPONSABILIDAD CIVIL EXTRACONTRACTUAL:',
  docFields: {
    municipio: 'CIRCASIA',
    municipioNombreCompleto: 'CIRCASIA QUINDÍO',
    municipioNit: '890.001.044-8',
    contrato: '001 DE 2015',
    tipoActa: 'ACTA DE OBRA',
    actaYear: '2026',
    actaFecha: '06 DE JULIO DE 2026',
    actaNumero: '01-2026',
    actaReferenciaAnterior: '01-2026',
    smmlvPresupuesto: '233,97',
    munNombre: 'JULIAN ANDRES PEÑA SIERRA',
    munCc: '1.010.043.054',
    munCcCiudad: 'Circasia',
    munCargo: 'Alcalde',
    munCargoFirma: 'Alcalde Municipal',
    munPosesionFecha: '02 de enero de 2024',
    munEntidad: 'MUNICIPIO DE CIRCASIA',
    conNombre: 'GLORIA LUCIA ESCALANTE MANZANO',
    conCc: '66.651.423',
    conCcCiudad: 'El Cerrito Valle del Cauca',
    conEmpresa: 'UNIÓN TEMPORAL ALUMBRADO PÚBLICO CIRCASIA',
    conNit: '900.883.379-9',
    intNombre: 'LUIS MIGUEL GRANJA BERMUDEZ',
    intCc: '10.347.784',
    intCcCiudad: 'Miranda Cauca',
    intEmpresa: 'CONSTRUTECNO S.A.S.',
    intCargo: 'Representante Legal',
  },

  consideraciones: [
    'Que el artículo 2 de la Constitución Política de Colombia de 1991 señala que son fines esenciales del Estado, servir a la comunidad, promover la prosperidad general y garantizar la efectividad de los principios, derechos y deberes consagrados en la constitución.',
    'Que conforme con el artículo 315 de la carta política de Colombia, corresponde a los alcaldes cumplir y hacer cumplir la constitución, la ley, los decretos del gobierno, las ordenanzas, los acuerdos de los concejos y dirigir la acción administrativa del municipio; asegurar el cumplimiento de las funciones y la prestación de los servicios a su cargo, en concordancia con el artículo 941 de la Ley 136 de 1994 modificado por el artículo 29 de la ley 1551 de 2012.',
    'Que el artículo 365 de la Constitución Política señala que los servicios públicos son inherentes a la finalidad social del Estado, debiendo garantizar su prestación eficiente a todos los habitantes del territorio nacional.',
    'Que el municipio abrió proceso de licitación pública No. 03-2014 para contratar mediante el sistema de CONCESIÓN, la prestación del servicio de Inversión, Administración, Operación, Mantenimiento, Reposición, Expansión y Desarrollo Tecnológico asociado al sistema de alumbrado público del Municipio de Circasia Quindío, suministrando el CONCESIONARIO a pleno costo los elementos, y asumiendo en fin, todo lo inherente y relacionado con el servicio de Alumbrado Público en todo el territorio del Municipio, a cambio de la remuneración pactada por las partes.',
    'Que el municipio adjudicó al CONCESIONARIO dicha licitación mediante Resolución No. 268 del 20 de agosto de 2015.',
    'Que, adjudicado el proceso de licitación, EL MUNICIPIO y EL CONCESIONARIO firmaron el CONTRATO DE CONCESIÓN No. 001 de fecha 14 de septiembre de 2015.',
    'Que el día 13 de noviembre de 2015, se inició la ejecución del contrato con la suscripción del acta de inicio.',
    'Que el día 12 de mayo de 2022 se suscribió modificatorio 4°, del contrato principal prorrogando el plazo inicial por diez (10) años más, quedando con una fecha final la del 13 de noviembre de 2045.',
    'Que de acuerdo con el Decreto 943 de 2018, el Alumbrado público es el servicio público no domiciliario que se presta con el objeto de proporcionar exclusivamente la iluminación de los espacios de uso público con tránsito vehicular o peatonal, dentro del perímetro urbano y rural de un municipio o distrito.',
    'Que el artículo 350 del Estatuto Tributario Ley 1819 de 2016 dispone que el impuesto de alumbrado público tiene una destinación exclusiva para la prestación, mejora, modernización y ampliación de la prestación del servicio de alumbrado público, incluyendo el suministro, administración, operación, mantenimiento, expansión y desarrollo tecnológico asociado.',
    'Que el servicio de alumbrado público comprende las actividades de suministro de energía eléctrica, se destina exclusivamente a la prestación, mejora, modernización y ampliación de la prestación del servicio de alumbrado público, incluyendo el suministro, administración, operación, mantenimiento, expansión y desarrollo tecnológico asociado, entre otros la realización de actividades de actos y alumbrado navideño.',
    'Que, con base en la anterior autorización, en el Otro Sí No. 2 del 8 de noviembre de 2017 se incluyó la CLÁUSULA TERCERA: ADICIÓNESE el párrafo cuarto a la cláusula novena del contrato de concesión No. 001 así: "CLÁUSULA NOVENA - RETRIBUCIÓN, FORMA Y CONDICIONES DE PAGO. EL MUNICIPIO retribuirá a EL CONCESIONARIO toda la prestación del servicio con el recaudo del IMPUESTO PARA EL SERVICIO DE ALUMBRADO PÚBLICO, pagados por los contribuyentes, recaudado por los agentes de retención o recaudo designados por EL MUNICIPIO y deducido del citado recaudo, única y exclusivamente, el costo mensual de la energía, el de la empresa del alumbrado público, el costo del servicio de interventoría y los costos del servicio de facturación y recaudo si los hubiere.\n\nDicho recaudo se hará a través del sistema financiero local y será administrado por la empresa fiduciaria que contratará el CONCESIONARIO para el manejo de los fondos de esta concesión. Los recursos deberán ingresar en su totalidad a la Fiducia de Administración y Pago contratada por EL CONCESIONARIO y sujeta a las reglas aquí establecidas. EL MUNICIPIO no podrá disponer de estos recursos cuando no se hayan cubierto los valores de las obligaciones aquí establecidas. La aplicación de los recursos será autorizada conjuntamente por EL CONCESIONARIO y el interventor designado por EL MUNICIPIO. Se precisará en el contrato de fiducia que el último beneficiario de recursos será EL MUNICIPIO, si se generan excedentes después de las obligaciones y que la ejecución de estos excedentes está a cargo exclusivo del CONCESIONARIO en virtud del contrato suscrito entre las partes y, en especial, que el destino de dichos excedentes deberá tener destinación específica, tal como el artículo 350 de la Ley 1819 de 2016, con los artículos primero y noveno del Decreto 943 de 2018 del Ministerio de Minas y Energía, que modificaron los artículos 2.2.3.1.2 y 2.2.3.6.1.7 del Decreto Único Reglamentario del Sector Administrativo de Minas y Energía No. 1073 de 2015, previa aprobación mediante Acta de Destinación de Excedentes entre EL CONCESIONARIO, EL MUNICIPIO y el interventor designado por EL MUNICIPIO.\n\nPara los casos de las obras de expansión o modernización se tendrán como base los precios establecidos mediante las Unidades Constructivas de Alumbrado Público (UCAPS) que se encuentran como anexo en el otrosí No. 1 y en los casos de iluminación navideña e iluminación ornamental se debe contar con cotizaciones que hagan parte del acta, igualmente se determinará el lugar, destinación, entre otros, de dichos excedentes.',
    'Para el pago de las actividades de lo definido por el Acta de Destinación de Excedentes, el interventor verifica que se cumplan las condiciones determinadas en la misma y a los precios acordados.',
    'El desarrollo de tales actividades dependerá de la existencia de recursos suficientes para ellas, y para su realización solo requerirá de actas firmadas para el efecto, por el Municipio, la Interventoría y el Concesionario.',
    'Que en el comité técnico mensual del 10 de marzo de 2025 se presentó la necesidad de expansión, cantidades y presupuesto, en el cual la administración municipal aprobó los proyectos que se describen en el presente documento con el valor determinado para ello.',
    'Que El Municipio cuenta con los recursos necesarios para la ejecución de las obras de expansión, según los saldos del recaudo del Impuesto de Alumbrado Público del Municipio de Circasia que se encuentran en la cuenta de la Fiducia del Banco de Bogotá y la destinación para la expansión por valor de {{VALOR_TOTAL}}.',
  ],

  clausulas: [
    { title: 'CLÁUSULA PRIMERA — OBJETO', content: 'Ejecutar por parte de la Union Temporal Alumbrado Público de Circasia, la obra de expansión con saldos del recaudo del impuesto de alumbrado público en los sitios: Vereda Piamonte (Trilladora Marrepo, Finca Almeguer), Vereda La Pola (Caserío), Vereda Membrillal (Caserío), Vereda Barcelona Baja (Caserío), Vereda La Cristalina (Caserío), Vereda Barcelona Alta (Finca Girasoles, Finca La Estrella, Finca Mi Tiendita), Vereda La Pola (Caserío), Barrio Alto Bonito, Barrio Las Américas (Calle 10 con Carrera 11ª), Barrio La Plancha (Bloque 6 Apto 102 Mz C), Barrio Villa Diana (Casas prefabricadas).' },
    { title: 'CLÁUSULA SEGUNDA — VALOR DEL PROYECTO', content: 'El valor total del proyecto de expansión es de {{VALOR_TOTAL}} distribuido en los diferentes proyectos aprobados de la siguiente manera:' },
    { title: 'CLÁUSULA TERCERA — FUENTE DE FINANCIAMIENTO', content: 'Los proyectos de expansión para iluminación del sistema de alumbrado público en el municipio de Circasia se ejecutarán con los excedentes del recaudo del Impuesto de Alumbrado Público, determinados en fiducia con corte a 30 de junio de 2025.' },
    { title: 'CLÁUSULA CUARTA — ALCANCE DE LAS OBRAS A EJECUTAR', content: 'La UTAP Circasia realizará la obra de expansión y puesta en funcionamiento en los sectores urbano y rural: Vereda Piamonte (Trilladora Marrepo, Finca Almeguer), Vereda La Pola (Caserío), Vereda Membrillal (Caserío), Vereda Barcelona Baja (Caserío), Vereda La Cristalina (Caserío), Vereda Barcelona Alta (Finca Girasoles, Finca La Estrella, Finca Mi Tiendita), Vereda La Pola (Caserío), Barrio Alto Bonito, Barrio Las Mercedes (Calle 10 con Carrera 11ª), Barrio La Plancha (Bloque 6 Apto 102 Mz C), Barrio Villa Diana (Casas prefabricadas).' },
    { title: 'CLÁUSULA QUINTA — ESPECIFICACIONES TÉCNICAS', content: 'El proyecto de iluminación se realizará con luminarias led de 35W y proyector led de 146W, brazos galvanizados de 1,5" x 1,5 uts., poste en fibra de vidrio de 9m y red en aluminio triplex #4 2x4+6 aérea.' },
    { title: 'CLÁUSULA SEXTA — OPERACIÓN Y MANTENIMIENTO', content: 'La infraestructura instalada queda a cargo del CONCESIONARIO en el marco del presente documento y del contrato de Concesión No. 001 de 2015 y se ingresarán los activos a los costos de AOM del CONCESIONARIO mediante la metodología actual de cobro CREG 123 de 2011.' },
    { title: 'CLÁUSULA SÉPTIMA — FORMA DE PAGO', content: 'EL MUNICIPIO pagará al CONCESIONARIO el valor total de la presente acta de obra No {{NUM_ACTA}}, a la firma del acta de inicio con saldos de fiducia del recaudo del impuesto de alumbrado público, la suma de {{VALOR_TOTAL}}, previa aprobación de garantías.' },
    { title: 'CLÁUSULA OCTAVA — VALOR PRESUPUESTO DE EXPANSIÓN CON EXCEDENTES', content: 'Los valores que conforman el presupuesto corresponden a las UCAPʼs aceptadas por el Municipio del 1 de Julio de 2015 y las nuevas UCAPʼs aprobadas mediante la presente Acta de Obra así:' },
    { title: 'CLÁUSULA NOVENA — PLAZO DE EJECUCIÓN', content: 'El plazo para la ejecución de los proyectos de Iluminación contemplados en la presente Acta de Obra es de ciento veinte (120) días hábiles contados a partir del inicio de ejecución de las obras, esto cuando se suscriba el acta de inicio.' },
    { title: 'CLÁUSULA DÉCIMA — GARANTÍAS', content: 'EL CONCESIONARIO deberá garantizar la ejecución del presente convenio, por tanto, deberá amparar a favor del Municipio de Circasia a través de cualquiera de los mecanismos de cobertura de riesgo permitidos por el Decreto 1082 de 2015.' },
    { title: 'CLÁUSULA DÉCIMA PRIMERA — PERFECCIONAMIENTO, LEGALIZACIÓN Y EJECUCIÓN', content: 'La presente acta se considerará perfeccionada con la suscripción del presente documento, por cada una de las partes, legalizada con el acta de aprobación de las pólizas y en ejecución con la suscripción del acta de inicio.\n\nEn constancia de aceptación se firma por las partes en dos (2) ejemplares al mismo tenor al día cinco (05) de julio de 2025.' },
  ],
};
