import type { ActaConfig } from './types';

export const guacariConfig: ActaConfig = {
  logoUrl: '/assets/images/logo-guacari.jpg',
  hideMunicipioBanner: true,
  docFields: {
    municipio: 'GUACARÍ',
    municipioNit: '',
    contrato: '',
    tipoActa: '',
    actaYear: String(new Date().getFullYear()),
    actaFecha: '',
    actaNumero: '',
    actaReferenciaAnterior: '',
    smmlvPresupuesto: '113.52',
    munNombre: '',
    munCc: '',
    munCcCiudad: '',
    munCargo: '',
    munPosesionFecha: '',
    conNombre: 'GLORIA LUCIA ESCALANTE MANZANO',
    conCc: '',
    conCcCiudad: '',
    conEmpresa: 'UNIÓN TEMPORAL DE ALUMBRADO PÚBLICO GUACARÍ',
    conNit: '',
    intNombre: '',
    intCc: '',
    intCcCiudad: '',
    intEmpresa: '',
  },

  consideraciones: [
    'Que el artículo 2 de la Constitución Política de Colombia de 1991 señala que son fines esenciales del Estado, servir a la comunidad, promover la prosperidad general y garantizar la efectividad de los principios, derechos y deberes consagrados en la constitución.',
    'Que conforme con el artículo 315 de la carta política de Colombia, corresponde a los alcaldes cumplir y hacer cumplir la constitución, la ley, los decretos del gobierno, las ordenanzas, los acuerdos de los concejos y dirigir la acción administrativa del municipio; asegurar el cumplimiento de las funciones y la prestación de los servicios a su cargo, en concordancia con el artículo 941 de la Ley 136 de 1994 modificado por el artículo 29 de la ley 1551 de 2012.',
    'Que el artículo 365 de la Constitución Política señala que los servicios públicos son inherentes a la finalidad social del Estado, debiendo garantizar su prestación eficiente a todos los habitantes del territorio nacional.',
    'Que el municipio aperturó proceso de licitación pública No LP-INF-001-2014 para contratar mediante el sistema de CONCESION, la prestación del servicio de Inversión, Administración, Operación, Mantenimiento, Reposición, Expansión y Desarrollo Tecnológico asociado al sistema de alumbrado público del Municipio de Guacarí, suministrando el CONCESIONARIO a pleno costo los elementos, y asumiendo en fin, todo lo inherente y relacionado con el servicio de Alumbrado Público en todo el territorio del Municipio, a cambio de la remuneración pactada por las partes.',
    'Que el municipio adjudicó al CONCESIONARIO dicha licitación mediante Resolución No. 100-033-516-2014 del tres (03) de diciembre de 2014.',
    'Que, adjudicado el proceso de licitación, EL MUNICIPIO y EL CONCESIONARIO firmaron el CONTRATO DE CONCESIÓN No. {{CONTRATO}} de fecha 18 diciembre de 2014.',
    'Que el servicio de alumbrado público comprende las actividades de suministro de energía al sistema de alumbrado público, la administración, la operación, el mantenimiento, la modernización, la reposición y la expansión del sistema de alumbrado público.',
    'Que en Sentencia C-055/19 de la corte constitucional, resolvió: "PRIMERO. ESTARSE A LO RESUELTO en la sentencia C-130 de 2018, en la cual se declaró EXEQUIBLE (i) la expresión "en la determinación del impuesto" contenida en el parágrafo 2° del artículo 349 de la Ley 1819 de 2016; y (ii) los apartes "exclusivamente" del artículo 350 y "de conformidad con la metodología para la determinación de costos establecida por el Ministerio de Minas y Energía, o la entidad que delegue el Ministerio" del artículo 351, ambos de la Ley 1819 de 2016". Negrilla y subrayados propios.',
    'Conforme al numeral que antecede el artículo 350 del Estatuto Tributario Ley 1819 de 2016, a la fecha goza plena validez, por lo tanto el impuesto de alumbrado público, tiene una destinación exclusiva para la prestación, mejora, modernización y ampliación de la prestación del servicio de alumbrado público, incluyendo el suministro, administración, operación, mantenimiento, expansión y desarrollo tecnológico asociado.',
    'Que en el otrosí modificatorio No. 04 del 10 de Noviembre de 2025 al contrato de concesión No. {{CONTRATO}}, del sistema de alumbrado público del Municipio de Guacarí, en la cláusula primera se estableció: ADICIONESE el párrafo cuarto a la cláusula novena del contrato de concesión No. 01 de 2014 así: "CLÁUSULA NOVENA - RETRIBUCIÓN, FORMA Y CONDICIONES DE PAGO. EL MUNICIPIO retribuirá a EL CONCESIONARIO toda la prestación del servicio con el recaudo del IMPUESTO PARA EL SERVICIO DE ALUMBRADO PUBLICO, pagados por los contribuyentes, recaudado por los agentes de retención o recaudo designados por EL MUNICIPIO y deducido del citado recaudo, única y exclusivamente, el costo mensual de la energía, el de la empresa del alumbrado público, el costo del servicio de interventoría y los costos del servicio de facturación y recaudo si los hubiere.\n\nDicho recaudo se hará a través del sistema financiero local y será administrado por la empresa fiduciaria que contratará el CONCESIONARIO para el manejo de los fondos de esta concesión. Los recursos deberán ingresar en su totalidad a la Fiducia de Administración y Pago contratada por EL CONCESIONARIO y sujeta a las reglas aquí establecidas. EL MUNICIPIO no podrá disponer de estos recursos cuando no se haya cubierto los valores de las obligaciones aquí establecidas. La aplicación de los recursos será autorizada conjuntamente por EL CONCESIONARIO y el interventor designado por EL MUNICIPIO. Se precisará en el contrato de fiducia que el último beneficiario de recursos será EL MUNICIPIO, si se generan excedentes después de las obligaciones y que la ejecución de estos excedentes está a cargo exclusivo del CONCESIONARIO en virtud del contrato suscrito entre las partes y, en especial, que el destino de dichos excedentes deberá tener destinación específica, tal como el artículo 350 de la Ley 1819 de 2016, con los artículos primero y noveno del Decreto 943 de 2018 del Ministerio de Minas y Energía, que modificaron los artículos 2.2.3.1.2 y 2.2.3.6.1.7 del Decreto Único Reglamentario del Sector Administrativo de Minas y Energía No. 1073 de 2015, previa aprobación mediante Acta de Destinación de Excedentes entre EL CONCESIONARIO, EL MUNICIPIO y el interventor designado por EL MUNICIPIO.\n\nPara los casos de las obras de expansión o modernización se tendrán como base los precios establecidos mediante las Unidades Constructivas de Alumbrado Público (UCAPS) que se encuentran como anexo en el otrosí No. 3 y en los casos de iluminación navideña e iluminación ornamental se debe contar con cotizaciones que hagan parte del acta, igualmente se determinará el lugar, destinación, entre otros, de dichos excedentes.',
    'Para el pago de las actividades de lo definido por el Acta de Destinación de Excedentes, el interventor verifica que se cumplan las condiciones determinadas en las misma y a los precios acordados.',
    'El desarrollo de tales actividades dependerá de la existencia de recursos suficientes para ellas, y para su realización solo requerirá de actas firmadas para el efecto, por el Municipio, la Interventoría y el Concesionario.',
    'Que en el comité técnico mensual del 20 de febrero de 2025 se presentó la necesidad de expansión, cantidades y presupuesto, en el cual la administración municipal aprobó los proyectos que se describen en el presente documento con el valor determinado para ello.',
    'Que El Municipio cuenta con los recursos necesarios para la ejecución de las obras de expansión, según los saldos del recaudo del Impuesto de Alumbrado Público del Municipio de Guacarí que se encuentran en la cuenta de la Fiducia del Banco de Bogotá y la destinación para la expansión por valor de {{VALOR_TOTAL}}.',
    'La interventoría verifica que los valores utilizados para la presente acta son los autorizados por el Municipio mediante las Unidades Constructivas de Alumbrado Público (UCAP) firmadas entre las partes y las nuevas UCAPsaprobadas mediante la presente acta, dando como resultado el valor total de cada proyecto, el cual, de acuerdo con la metodología para el cálculo de los costos máximos de la prestación del servicio de alumbrado público debe ser actualizada mediante la indexación con el índice de precios al productor de oferta interna.',
  ],

  clausulas: [
    { title: 'CLÁUSULA PRIMERA — OBJETO', content: '"Ejecutar por parte de la empresa Unión Temporal Alumbrado Público Guacarí, la obra de expansión con saldos del recaudo del impuesto de alumbrado público en el sector del Callejón de Chivirí, zona rural del Municipio.' },
    { title: 'CLÁUSULA SEGUNDA — VALOR DEL PROYECTO', content: 'El valor total del proyecto de la expansión es de {{VALOR_TOTAL}}.' },
    { title: 'PARÁGRAFO — FUENTE DE FINANCIAMIENTO', content: 'El proyecto de expansión para iluminación del sistema de alumbrado público en el municipio de Guacarí se ejecutará con los saldos del recaudo del Impuesto de Alumbrado Público, determinados en fiducia con corte a 31 de octubre de 2025.' },
    { title: 'CLÁUSULA TERCERA — ALCANCE DE LAS OBRAS A EJECUTAR', content: 'Realizar la obra de expansión que pertenece al Plan Anual 2025 iluminando y dejando en funcionamiento el sector detallado a continuación:' },
    { title: 'CLÁUSULA CUARTA — ESPECIFICACIONES TÉCNICAS', content: 'Las obras de iluminación se ejecutarán con luminarias led de 56W, brazos galvanizados, postes de fibra de vidrio y red triplex # 4 Aislada de aluminio.' },
    { title: 'CLÁUSULA QUINTA — OPERACIÓN Y MANTENIMIENTO', content: 'La infraestructura instalada queda a cargo del CONCESIONARIO en el marco del presente documento y del contrato de Concesión No. {{CONTRATO}} y se ingresarán los activos a los costos de AOM del CONCESIONARIO mediante la metodología actual de cobro CREG 123 de 2011.' },
    { title: 'CLÁUSULA SEXTA — FORMA DE PAGO', content: 'EL MUNICIPIO pagará al CONCESIONARIO el valor total de la presente acta de obra No {{NUM_ACTA}}, a la firma del acta de inicio con saldos de fiducia del recaudo del impuesto de alumbrado público, la suma de {{VALOR_TOTAL}}. previa aprobación de garantías.' },
    { title: 'CLÁUSULA SÉPTIMA — VALOR PRESUPUESTO DE EXPANSIÓN', content: 'Los valores que conforman el presupuesto corresponden a las UCAP\'s aceptadas por el Municipio así:' },
    { title: 'CLÁUSULA OCTAVA — PLAZO DE EJECUCIÓN', content: 'El plazo para la ejecución de los proyectos de Iluminación contemplados en la presente Acta de Obra es de ciento veinte (120) días hábiles contados a partir del inicio de ejecución de las obras, esto cuando se suscriba el acta de inicio.' },
    { title: 'CLÁUSULA NOVENA — GARANTÍAS', content: 'EL CONCESIONARIO deberá garantizar la ejecución del presente convenio, por tanto, deberá amparar a favor del Municipio a través de cualquiera de los mecanismos de cobertura de riesgo permitidos por el Decreto 1082 de 2015.' },
    { title: 'CLÁUSULA DÉCIMA — PERFECCIONAMIENTO, LEGALIZACIÓN', content: 'La presente acta se considerará perfeccionada con la suscripción del presente documento, por cada una de las partes, legalizada con el acta de aprobación de las pólizas y en ejecución con la suscripción del acta de inicio.\n\nPara constancia se firma por las partes en dos (2) ejemplares al mismo tenor a los veinte (20) días del mes de noviembre de dos mil veinticinco (2025).' },
  ],
};
