import type { ActaConfig } from './types';

export const guacariConfig: ActaConfig = {
  logoUrl: '/assets/images/logo-guacari.jpg',
  hideMunicipioBanner: true,
  insertTablesAfterClauseTitle: 'SÉPTIMA',
  garantiaCumplimientoTitle: 'I. GARANTÍA DE CUMPLIMIENTO DEL CONTRATO Y DEVOLUCIÓN DEL PAGO ANTICIPADO:',
  garantiaRceTitle: 'II. GARANTÍA DE RESPONSABILIDAD CIVIL EXTRACONTRACTUAL:',
  tituloLineas: [
    'SISTEMA DE ALUMBRADO PÚBLICO DEL MUNICIPIO DE {{municipio}}',
    'CONTRATO DE CONCESIÓN No {{contrato}}',
    'ACTA DE AUTORIZACIÓN No. {{actaNumero}}',
    'EXPANSIÓN DEL SISTEMA DE ALUMBRADO PÚBLICO',
    '({{actaFecha}})',
  ],
  docFields: {
    municipio: 'GUACARÍ',
    municipioNit: '891.380.089-7',
    contrato: 'CSAP-001-2015',
    tipoActa: 'EXPANSIÓN DEL SISTEMA DE ALUMBRADO PÚBLICO',
    actaYear: '2026',
    actaFecha: '15 DE MAYO DE 2026',
    actaNumero: '02-2026',
    actaReferenciaAnterior: '02-2026',
    smmlvPresupuesto: '190.69',
    munNombre: 'LEONOR ABADÍA BENITEZ',
    munCc: '38.852.714',
    munCcCiudad: 'Buga, Valle',
    munCargo: 'Alcaldesa',
    munCargoFirma: 'Alcaldesa Municipal',
    munPosesionFecha: '01 de enero de 2024',
    conNombre: 'GLORIA LUCIA ESCALANTE MANZANO',
    conCc: '66.651.423',
    conCcCiudad: 'El Cerrito Valle del Cauca',
    conEmpresa: 'UNIÓN TEMPORAL DE ALUMBRADO PÚBLICO GUACARÍ',
    conEmpresaFirma: 'UTAP Guacarí',
    conNit: '900.797.627-2',
    intNombre: 'SOFONIAS BANGUERO ZAPATA',
    intCc: '19.380.232',
    intCcCiudad: 'Bogotá',
    intEmpresa: 'INGENIERIA Y SOPORTE S.B.Z S.A.S',
  },

  partesIntroTemplate:
    'Entre los suscritos {{munNombre}}, mayor de edad, identificada con cédula de ciudadanía No. {{munCc}} de {{munCcCiudad}}, quien obra en nombre y representación del MUNICIPIO DE {{municipio}}, en su calidad de {{munCargo}}, de conformidad con el Acta de Posesión del {{munPosesionFecha}}, quien en adelante para los efectos del presente documento se denominará EL MUNICIPIO, por una parte, {{conNombre}}, mayor de edad, identificada con cédula de ciudadanía No. {{conCc}} de {{conCcCiudad}}, quien actúa en calidad de Representante Legal de la {{conEmpresa}}, identificada con No. De Nit {{conNit}}, quien en adelante para los efectos del presente documento se denominará EL CONCESIONARIO, y por otra parte {{intNombre}}, mayor de edad, identificado con cédula de ciudadanía No. {{intCc}} expedida en {{intCcCiudad}}, quien actúa en calidad de representante legal de {{intEmpresa}} y Director de Interventoría del Contrato de Concesión, hemos convenido suscribir la presente acta de autorización No. {{actaNumero}} para la realización de expansiones en diferentes sectores de la zona urbana y rural del Municipio de {{municipio}} en el año {{actaYear}}, en el marco del contrato de Concesión No. {{contrato}}, la cual se regirá por las siguientes cláusulas, previas las siguientes.',

  preAcuerdanText: 'Que, con fundamento en lo anterior, las partes',

  consideraciones: [
    'Que el artículo 2 de la Constitución Política de Colombia de 1991 señala que son fines esenciales del Estado, servir a la comunidad, promover la prosperidad general y garantizar la efectividad de los principios, derechos y deberes consagrados en la constitución.',
    'Que conforme con el artículo 315 de la carta política de Colombia, corresponde a los alcaldes cumplir y hacer cumplir la constitución, la ley, los decretos del gobierno, las ordenanzas, los acuerdos de los concejos y dirigir la acción administrativa del municipio; asegurar el cumplimiento de las funciones y la prestación de los servicios a su cargo, en concordancia con el artículo 941 de la Ley 136 de 1994 modificado por el artículo 29 de la ley 1551 de 2012.',
    'Que el artículo 365 de la Constitución Política señala que los servicios públicos son inherentes a la finalidad social del Estado, debiendo garantizar su prestación eficiente a todos los habitantes del territorio nacional.',
    'Que el municipio aperturo proceso de licitación pública No LP-INF-001-2014 para contratar mediante el sistema de CONCESIÓN, la prestación de servicio de Inversión, Administración, Operación, Mantenimiento, Reposición, Expansión y Desarrollo Tecnológico asociado al sistema de alumbrado público del Municipio de Guacarí, suministrando el CONCESIONARIO a pleno costo los elementos, y asumiendo en fin, todo lo inherente y relacionado con el servicio de Alumbrado Público en todo el territorio del Municipio, a cambio de la remuneración pactada por las partes.',
    'Que el municipio adjudicó al CONCESIONARIO dicha licitación mediante Resolución No. 100-033-516-2014 del tres (03) de diciembre de 2014.',
    'Que, adjudicado el proceso de licitación, EL MUNICIPIO y EL CONCESIONARIO firmaron el CONTRATO DE CONCESIÓN No. CSAP-001-2015 de fecha 18 diciembre de 2014.',
    'Que el servicio de alumbrado público comprende las actividades de suministro de energía al sistema de alumbrado público, la administración, la operación, el mantenimiento, la modernización, la reposición y la expansión del sistema de alumbrado público.',
    'Que en Sentencia C-055/19 de la corte constitucional, resolvió: "PRIMERO. ESTARSE A LO RESUELTO en la sentencia C-130 de 2018, en la cual se declaró EXEQUIBLE (i) la expresión "en la determinación del impuesto" contenida en el parágrafo 2° del artículo 349 de la Ley 1819 de 2016; (ii) los apartes "exclusivamente" del artículo 350 y "de conformidad con la metodología para la determinación de costos establecida por el Ministerio de Minas y Energía, o la entidad que delegue el Ministerio" del artículo 351, ambos de la Ley 1819 de 2016". Negrilla y subrayados propios.',
    'Conforme al numeral que antecede el artículo 350 del Estatuto Tributario Ley 1819 de 2016, a la fecha goza plena validez, por lo tanto el impuesto de alumbrado público, tiene una destinación exclusiva para la prestación, mejora, modernización y ampliación de la prestación del servicio de alumbrado público, incluyendo el suministro, administración, operación, mantenimiento, expansión y desarrollo tecnológico asociado.',
    'Que en el otrosí modificatorio No. 04 del 10 de noviembre de 2025 al contrato de concesión No. CSAP-001-2015, del sistema de alumbrado público del Municipio de Guacarí, en la cláusula primera se estableció: ADICIÓNESE el parágrafo cuarto a la cláusula novena del contrato de concesión No. 01 de 2014 así: "CLÁUSULA NOVENA - RETRIBUCIÓN, FORMA Y CONDICIONES DE PAGO. EL MUNICIPIO retribuirá a EL CONCESIONARIO toda la prestación del servicio con el recaudo del IMPUESTO PARA EL SERVICIO DE ALUMBRADO PÚBLICO, pagados por los contribuyentes, recaudado por los agentes de retención o recaudo designados por EL MUNICIPIO y deducido del citado recaudo, única y exclusivamente, el costo mensual del consumo de energía eléctrica del alumbrado público, el costo del servicio de interventoría y los costos del servicio de facturación y recaudo si los hubiere.\n\nDicho recaudo se hará a través del sistema financiero local y será administrado por la empresa fiduciaria que contratará el CONCESIONARIO para el manejo de los fondos de esta concesión. Los recursos deberán ingresar en su totalidad a la Fiducia de Administración y Pagos contratada por EL CONCESIONARIO y sujeta a las reglas aquí establecidas. EL MUNICIPIO no podrá disponer de los recursos en tanto no se haya cubierto los valores de las obligaciones aquí establecidas. La aplicación de los recursos será autorizada conjuntamente por EL CONCESIONARIO y el interventor designado por EL MUNICIPIO. Se precisará en el contrato de fiducia que el último beneficiario de recursos será EL MUNICIPIO, si se generan excedentes después de las obligaciones y que la ejecución de estos excedentes está a cargo exclusivo de EL CONCESIONARIO en virtud del contrato suscrito entre las partes y, en especial, que el Impuesto de Alumbrado Público tiene una destinación específica, tal como el artículo 350 de la Ley 1819 de 2016, con los artículos primero y noveno del Decreto 943 de 2018 del Ministerio de Minas y Energía, que modificaron los artículos 2.2.3.1.2 y 2.2.3.6.1.7 del Decreto Único Reglamentario del Sector Administrativo de Minas y Energía, 1073 de 2015, previa aprobación mediante Acta de Destinación de Excedentes entre EL CONCESIONARIO, EL MUNICIPIO y el interventor designado por EL MUNICIPIO.\n\nPara los casos de las obras de expansión o modernización se tendrán como base los precios establecidos mediante las Unidades Constructivas de Alumbrado Público (UCAPS) que se encuentran como anexo en el otrosí No. 3 y en los casos de iluminación navideña e iluminación ornamental se debe contar con cotizaciones que harán parte del acta, igualmente se determinará el lugar, destinación, entre otros, de dichos excedentes.',
    'Para el pago de las actividades de lo definido por el Acta de Destinación de Excedentes, el interventor verifica que se cumplan las condiciones determinadas en las mismas y a los precios acordados.',
    'El desarrollo de tales actividades dependerá de la existencia de recursos suficientes para ellas, y para su realización solo requerirá de actas firmadas para el efecto, por el Municipio, la Interventoría y el Concesionario.',
    'Que en reunión del 26 de marzo del presente año se presentó la necesidad de expansión, cantidades y presupuesto, en el cual la administración municipal aprobó los proyectos que se describen en el presente documento con el valor determinado para ello.',
    'Que El Municipio cuenta con los recursos necesarios para la ejecución de las obras de expansión, según los saldos del recaudo del Impuesto de Alumbrado Público del Municipio de Guacarí que se encuentran en la cuenta de la Fiducia del Banco de Bogotá y la destinación para la expansión por valor de trescientos treinta y tres millones ochocientos ochenta y dos mil novecientos cuarenta y tres pesos moneda legal ($333.882.943) M/L.',
    'La interventoría verifica que los valores utilizados para la presente acta son los autorizados por el Municipio mediante las Unidades Constructivas de Alumbrado Público (UCAP) firmadas entre las partes y las nuevas UCAPs aprobadas mediante la presente acta, dando como resultado el valor total de cada proyecto, el cual, de acuerdo con la metodología para el cálculo de los costos máximos de la prestación del servicio de alumbrado público debe ser actualizado mediante la indexación con el índice de precios al productor de oferta interna.',
  ],

  clausulas: [
    { title: 'CLÁUSULA PRIMERA — OBJETO', content: '"Ejecutar por parte de la empresa Unión Temporal Alumbrado Público Guacarí, expansiones con saldos del recaudo del impuesto de alumbrado público en zona urbana y rural del Municipio.' },
    { title: 'CLÁUSULA SEGUNDA — VALOR DEL PROYECTO', content: 'El valor total del proyecto de la expansión es de trescientos treinta y tres millones ochocientos ochenta y dos mil novecientos cuarenta y tres pesos moneda legal ($333.882.943) M/L.' },
    { title: 'PARÁGRAFO — FUENTE DE FINANCIAMIENTO', content: 'El proyecto de expansión para iluminación del sistema de alumbrado público en el municipio de Guacarí se ejecutará con los saldos del recaudo del Impuesto de Alumbrado Público, determinados en fiducia con corte a 31 de marzo de 2026.' },
    { title: 'CLÁUSULA TERCERA — ALCANCE DE LAS OBRAS A EJECUTAR', content: 'Realizar la obra de expansión que pertenece al Plan Anual 2026 iluminando y dejando en funcionamiento los diferentes sectores detallados a continuación:' },
    { title: 'CLÁUSULA CUARTA — ESPECIFICACIONES TÉCNICAS', content: 'Las expansiones se ejecutarán con luminarias de tecnología LED de potencias 35, 56 y 80 W, proyectores de tecnología LED de 150 W de potencia, brazos galvanizados, postes de fibra de vidrio de 9 metros de alto y red triplex # 4 Aislada de aluminio.' },
    { title: 'CLÁUSULA QUINTA — OPERACIÓN Y MANTENIMIENTO', content: 'La infraestructura instalada queda a cargo del CONCESIONARIO en el marco del presente documento y del contrato de Concesión No. CSAP-001-2015 y se ingresarán los activos a los costos de AOM del CONCESIONARIO mediante la metodología actual de cobro CREG 123 de 2011.' },
    { title: 'CLÁUSULA SEXTA — FORMA DE PAGO', content: 'El MUNICIPIO pagará al CONCESIONARIO el valor total de la presente acta No. 02-2026, a la firma del acta de inicio con saldos de fiducia del recaudo del impuesto de alumbrado público, la suma de trescientos treinta y tres millones ochocientos ochenta y dos mil novecientos cuarenta y tres pesos moneda legal ($333.882.943) M/L. previa aprobación de garantías.' },
    { title: 'CLÁUSULA SÉPTIMA — VALOR PRESUPUESTO DE EXPANSIÓN', content: 'Los valores que conforman el presupuesto corresponden a las UCAP\'s aceptadas por el Municipio así:' },
    { title: 'CLÁUSULA OCTAVA — PLAZO DE EJECUCIÓN', content: 'El plazo para la ejecución de los proyectos de Iluminación contemplados en la presente Acta de Autorización es de ciento veinte (120) días hábiles contados a partir del inicio de ejecución de las obras, esto cuando se suscriba el acta de inicio.' },
    { title: 'CLÁUSULA NOVENA — GARANTÍAS', content: 'EL CONCESIONARIO deberá garantizar la ejecución del presente convenio, por tanto, deberá amparar a favor del Municipio a través de cualquiera de los mecanismos de cobertura de riesgo permitidos por el Decreto 1082 de 2015.' },
    { title: 'CLÁUSULA DÉCIMA — PERFECCIONAMIENTO, LEGALIZACIÓN', content: 'La presente acta se considerará perfeccionada con la suscripción del presente documento, por cada una de las partes, legalizada con el acta de aprobación de las pólizas y en ejecución con la suscripción del acta de inicio.\n\nPara constancia se firma por las partes en dos (2) ejemplares al mismo tenor a los quince (15) días del mes de mayo de dos mil veintiséis (2026).' },
  ],
};
